server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: contribuyente
          uri: http://localhost:8081
          predicates: [ Path=/api/contribuyente/** ]
        - id: vehiculo
          uri: http://localhost:8082
          predicates: [ Path=/api/vehiculo/** ]
        - id: licencia
          uri: http://localhost:8083
          predicates: [ Path=/api/licencia/** ]
